language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
before_install:
  - travis_retry composer self-update
  - composer install
script: ./vendor/bin/phpunit
after_success:
  - travis_retry php vendor/bin/php-coveralls
